version: "3.7"

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonarnet

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - sonarqube
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/services:/etc/nginx/services
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sonarnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    expose:
      - "8080:8080"
    ports:
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sonarnet

networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  jenkins_data:
